# Generated by Django 5.0.3 on 2024-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
